### PR TITLE
Improvement/ofnl params and t0

### PR DESCRIPTION
**Pull request by nick-mast**
Finally got around to pushing the ofnl improvements discussed in #49 and #50.

### CODE REVIEW

**Comment by nick-mast** [comment]
No sorry needed, I think it's unclear what the best way to proceed is, so we need such discussion! 

On the one hand, it would be good to have consistent behavior between the 1,2,3,4-pole options. For 2-pole, the pulse height is a natural and useful parameter and we can easily convert from it to the parameter A (excepting the rare case of tau_r=tau_f). With 3,4-poles, the parameters are not connected to height in an analytically solvable way, so the A, B, C params are more natural. If you want to calculate the 3,4-pole fit pulse height or integral or their variances, it can get messy. Since there are lots of complicated things you can do with the best fit parameter results (pulse height, integral, integral with 2nd order term, ...), this makes me feel like we should just leave this function as a fitting utility and let the user make something that connects the results to physics.

However, you raise good points. We should always strive for backwards compatibility. Also, just because the 3,4-pole things get messy, does that justify not letting 1,2-pole return in terms of pulse height (which is very useful)? But I also hate to have these special flags that are only relevant for 1,2-pole.

idk

**Comment by cwfink** [comment]
Yeah, I agree having a bunch of super specific flags is sort of a messy. We should think of the best way to do this, but I just wanted to add that the initial motivation for writing this tool was to do the 1-2 pole fit. The 3-4 pole fits were added after the fact in an ad hoc manner. So I sort of feel that the 3-4 pole fits should have less weight in the decision of how to standardize the functions.

**Comment by nick-mast** [comment]
Alright, I guess your original suggestion is an okay compromise. I don't see a better way to keep from having to rewrite all the existing code that uses this _and_ have the option to use this new functional form. I'll make that change.

**Comment by slwatkins** [comment]
FYI, I tacked on a commit that does some white space and docstring fixes for the `qetpy.OFnonlin` class - didn't change any code though!

**Pull request merged**
